### ISSUE TITLE
Video playback blocked by uBlock Origin filter "llacb47/miscfilters/anti-serviceworker'

### ISSUE THREAD

**Issue by FuccDucc** [Sommerwiesel/invidious#5]
Just as a heads-up to the users and maintainer of this indivious endpoint (created an issue on the repo that causes this issue; [https://github.com/llacb47/miscfilters/issues/49](https://github.com/llacb47/miscfilters/issues/49))

Video playback won't work (infinite spinner when you click play) when Invidious chooses nerdvpn.de as Invidious endpoint, in case the user has uBlock Origin that uses the following blocklist: [anti-serviceworker](https://github.com/llacb47/miscfilters/blob/master/discontinued/anti-serviceworker.txt)

I did reproduce using the following video on your specific individious instance: [https://invidious.nerdvpn.de/watch?v=-lz30by8-sU](https://invidious.nerdvpn.de/watch?v=-lz30by8-sU) and if it matters, it was on Firefox.

I wonder, but highly suspect, that other Invidious instances, at the very least those based on your fork, are also affected, thus i will recommend the filter repo operator to add pages that identify as indivious instances to whitelist.

Also, why does your instance technology use service workers? Many anti-tracking addons don't like service workers, if you can get around the use of it, it may be better.

Other indivious endpoints work properly.

**Comment by Sommerwiesel** [comment]
Hey @FuccDucc,
I've only seen this issue now, my github didn't notify me via email.

I want to reopen this because of what you said about service workers, specifically:

`Also, why does your instance technology use service workers? Many anti-tracking addons don't like service workers, if you can get around the use of it, it may be better.`

I have to confess that I don't really understand what you're talking about. Can you elaborate on this?
I'm planning to migrate my instance to a new server on 18-12-2022 and if there's a way to get around using those service workers, I'm all in.

Cheers,
Marvin

**Comment by Sommerwiesel** [comment]
After Fürther investigation, I found out that my instance is not using any kind of service workers.
Therefore, closed.
