### ISSUE TITLE
Country restriction????? REALLY?

### ISSUE THREAD

**Issue by arash74** [Sommerwiesel/invidious#6]
"Access to this Invidious instance is country restricted"
WHAT IS THIS NOW? YOUTUBE OFFICIAL? This is unbelievable. 
And you have the nerve to put Iran on the blacklist. A country in which the dictator government blocks Youtube access. WOW. JUST WOW.

**Comment by andrigamerita** [comment]
> And you have the nerve to put Iran on the blacklist.

@arash74 Here I suspect that, most likely, they have put only Germany on the whitelist and thus all other countries are blocked.  
I'm in Italy and until yesterday the instance was accessible to me, since today it isn't.

---

To the instance maintainer(s): I want to know why though? Too few resources to handle too many people for a free-of-charge service or what? From one day to the next without prior notice of any kind is kind of bad.

Also, I'd question the legality of the whole operation, since the instance is hosted in Europe, and it is a public service, it has to follow GDPR, but afaik (I might be mistaken, I'm not a lawyer) it's against the regulation to deny people access to the service without a prior notice if you don't both provide a data backup and allow for deletion of personal data from the servers.  
I exported my data and then deleted my account by connecting to the server with a free VPN (German IP address), but I've been able to do this only because I know how to do this kind of stuff, some people might not. On the "access restricted" page, I think you should provide an email address for someone to contact you to ask for both a data export and account deletion.

**Comment by FuccDucc** [comment]
I didn't confirm that they blocked countries except for Germany (it seems to work for me at this moment), but if they did or are about to finalize such an action, it's not a big deal.. just use [LibRedirect](https://addons.mozilla.org/en-US/firefox/addon/libredirect/) that dynamically chooses from invidious front-ends.

Then we report the indivious "NerdVPN.de" front-end to LibRedirect devs (to get it removed) for its egocentric action of blocking users on the basis of nationality, so that people no longer get it dynamically assigned. NerdVPN should realize that they are just a tiny dot in the pool of available instances, in fact i only saw it existed after getting it assigned by LibRedirect once in the past year.. and that still, due to the high amount of LibRedirect users, actions like this will turn the trickle of their randomly selected users to nothing. Which is good on parties that exhibit this kind of antisocial/discriminative behavior.

**Comment by FuccDucc** [comment]
Update to my last comment.. i was able to confirm these negative practises. The block doesn't affect my own country (Netherlands) but affects many others, like France, USA etc, as tested from different connections.

This is the "Your country is blocked" page that i was able to confirm:

![image](https://user-images.githubusercontent.com/61570793/204129209-c3f0159e-acb2-447a-91f4-4e73b41a0f0d.png)

Now that it's confirmed, i will turn right around and go ahead in asking LibRedirect to ban the NerdVPN Invidious instances.

**Comment by Sommerwiesel** [comment]
Cheers everyone,
sorry for the late reply, the past weeks have been kinda hard on me.
This whole thing started when my server was under hard attack from basically everywhere and I had to start taking measurements against it.
Suddenly, my 20TB of included monthly traffic was at 163TB (which I had to pay with a quite high price) and I wanted to look into the whole mess.
It was not legit traffic at this point but a lot of requests that tried to seemingly use my instance as a way to download huge portions of Youtube.
MY first reaction was to try fighting this with the methods given to you by Invidious: disable downloading, disable local proxy. But that didn't work at all.
My second attemt was at including a rate limiter for everyone trying to fetch huge amounts of data but that didn't bode well with Invidious hourly restart.
My third attempt, and at this point I was angry, frustrated and mostly out of time to properly look into this problem, was to just block out all coutnries which data volume has gone over and beyond a reasonable value.

I know now that with the last option, I was completely out of my mind and I want to take this opportunity to apologize to everyone involved.
I have disabled all limitations again and hereby vouch to never use such drastic and plainly wrong methods again.

I'm currently thinking about moving the server to a place where traffic is not a monetary issue. I should have done that in the first place, but didn't find time for it.

Again, verry sorry about this.
I hope you can forgive me, I have absolutely learned this lesson ad will take it to heart.

Cheers,
Marvin

**Comment by unixfox** [comment]
@Sommerwiesel On these kinds of decisions, you may also consult the community of Invidious. Plenty of other Invidious instance maintainers have probably run into the same issue.

If you had reached out to the Invidious team, we would have given you better advices than straight blocking people. I run yewtu.be, and I would surely have helped you in overcoming this issue.

If you have a matrix account, we can add you in the matrix channel, where a lot of invidious instance maintainers can talk between each other. Join our matrix channel and send us a ping if you are interested: https://matrix.to/#/#invidious:matrix.org

Anyway, for the future, like you said, it's hugely recommended to run the invidious instance on a server with unlimited traffic. Video playback consumes a lot of bandwidth, it's not lightweight on bandwidth like Nitter or Searx.

**Comment by FuccDucc** [comment]
I noticed the discussion surrounding this matter at places, like: https://github.com/iv-org/documentation/issues/149 (comments at the very bottom, including what Ammako called him bringing it up with them), [https://github.com/iv-org/documentation/issues/241#issuecomment-1337055573](https://github.com/iv-org/documentation/issues/241#issuecomment-1337055573) and especially here, after which i believe and understand what the instance operator is saying. Looks resolved to me

Btw, when you described the Europe thing.. it's kinda odd that countries like France also ended up blacklisted then (as stated in my original posts). But whatever

**Comment by Sommerwiesel** [comment]
> Btw, when you described the Europe thing.. it's kinda odd that countries like France also ended up blacklisted then (as stated in my original posts). But whatever

Short answer: IP-based blocking is shiiiiit, especially if you're not a paying Maxmind customer ;)

Thanks for all the feedback everyone, especially from @unixfox. 
I have already taken proper measurments by migrating the instance to a new dedicated server without any kind of traffic limit. 
I will, as soon as I find the time (which means after Christmas), reach out to you on matrix and continue discussing things like this over there.

I have also thought about getting one of my friends involved in managing the servers as well as participating in decision making. It seems like managing all the services on my own isn't such a good idea after all...

Have a nice December and love from Germany,
Marvin
